---
functional:
  - Неавторизованный пользователь должен иметь возможность решить рандомную задачу без регистрации
  - Неавторизованный пользователь должен иметь возможность просматривать главную страницу сайта
  - Пользователь должен иметь возможность войти в систему
  - Авторизованный пользователь должен иметь возможность выбора задач
  - Авторизованный пользователь должен иметь возможность участвовать в процессе решения выбранной задач
  - Авторизованный пользователь должен иметь возможность просматривать рейтинг играков
  - Авторизованный пользователь должен иметь возможность просмотра таблиц лобби, турниры и завершенные игры
  - Авторизованный пользователь должен иметь возможность создавать новые задачи
  - Авторизованный пользователь должен иметь возможность сгруппировать существующие задачи
  - Авторизованный пользователь должен иметь возможность создавать новые турниры
  - Авторизованный пользователь должен иметь возможность быть участником турниров
  - Авторизованный пользователь должен иметь возможность просматривать записи и результаты прошедших состязаний
  - Авторизованный пользователь должен иметь возможность просматривать свой профиль
  - Авторизованный пользователь должен иметь возможность регулировать настройки своего профиля
  - Авторизованный пользователь должен иметь возможность просматривать профиль других игроков
  - Авторизованный пользователь должен иметь возможность наблюдать за активным состязанием 
  - Авторизованный пользователь должен иметь возможность отправлять сообщения в глобальном чате
  - Авторизованный пользователь должен иметь возможность отправлять личное сообщения в приватном канале другому пользователю
  - Пользователь должен иметь возможность отправлять сообщения в чате в сессии задачи
  - Пользователь должен иметь возможность воспользоваться гидом/помощником, который объясняет основные аспектах игры
  - Пользователь должен иметь возможность выбирать язык программирования в сессии задачи
  - Пользователь должен иметь возможность завершить сессию задачи в любой момент (Give up button)
  - Пользватель должен иметь возможность начать сессию задачи заново (Reset button)
  - Пользватель должен иметь возможность проверить решение задачи (Check button)
  - Пользватель должен иметь возможность писать решение в редакторе задачи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен поддерживать локализацию
implicit:
  - Динамическое обновление данных на страницах без принудительной перезагрузки сайта
  - Предупреждение об использовании cookie
  - Проверка и вывод всех ошибок на странице Авторизации, если логин и почта невалидные или уже используются # на данный момент проверка корректности логина и почты проверяются последовательно
